### ISSUE TITLE
ReferenceError: me is not defined

### ISSUE THREAD

**Issue by igdev116** [KingSora/OverlayScrollbars#406] opened 2021-12-15 05:54 UTC
When I build product with Next Js, an error is occurred but during development nothing happens 😢
```
framework-9e9e884da035a686.js:1 ReferenceError: me is not defined
    at 632cba62-656fef5300583a9d.js:1
    at HTMLDivElement.<anonymous> (632cba62-656fef5300583a9d.js:1)
    at Function.r [as each] (632cba62-656fef5300583a9d.js:1)
    at a.OverlayScrollbars (632cba62-656fef5300583a9d.js:1)
    at g.componentDidMount (0-e5f8904c82d78800.js:1)
    at kh (framework-9e9e884da035a686.js:1)
    at zi (framework-9e9e884da035a686.js:1)
    at b.unstable_runWithPriority (framework-9e9e884da035a686.js:1)
    at Qe (framework-9e9e884da035a686.js:1)
    at yi (framework-9e9e884da035a686.js:1)
```

**Comment by tamimaj** [comment] 2022-01-31 22:58
Same here!
Did you find the cause?

**Comment by KingSora** [comment] 2022-11-12 13:16
Please try the new `v2` version of `overlayscrollbars` and the most recent version of `overlayscrollbars-react`. This should be fixed there

**Closed by KingSora** 2022-11-12 13:16 UTC
