### ISSUE TITLE
Cannot scroll when the mouse is over a fixed element.

### ISSUE THREAD

**Issue by hallaji** [KingSora/OverlayScrollbars#261] opened 2020-09-06 11:32 UTC
Hi there 👋

I've got a navigation bar at the top of my page with `fixed` position and initialised the scroll on the body element. However, the scroll is not working when the mouse is over fixed element. I have to move mouse out of navigation bar in order to scroll the page.

Is this expected behaviour? How may I fix this issue? I would like to scroll even when the mouse is over a fixed element.

**Environment**
 - Used Operating System(s): macOS Catalina 10.15.6
 - Used Browser(s) (with version): Google Chrome 85.0.4183.83

**Comment by KingSora** [comment] 2020-09-09 17:42
Good day!
This is related or a duplicate of #249, please check out the issue and give feedback wether it helped you.

**Closed** 2020-09-10 02:19 UTC
