### ISSUE TITLE
Scroll method not working on dynamic content

### ISSUE THREAD

**Issue by pollux4321** [KingSora/OverlayScrollbars#155] opened 2019-11-15 07:04 UTC
I'm grabbing content from server and loading to DOM, initializing scrollbars and then trying to position the scroll at bottom. The initialization works but the scroll does not.

```
                                    var messagesScroll = $(".messages").overlayScrollbars({
                                        "paddingAbsolute" : true,
                                        overflowBehavior : {
                                            "x" : "visible-hidden",
                                            "y" : "scroll"
                                        },
                                        scrollbars : {
                                            "autoHide" : "leave",
                                            "autoHideDelay" : 100,
                                        }
                                    }).overlayScrollbars();
                                    messagesScroll.scroll("100%"); // or ({ y : "100%"}) same result
```

**Comment by pollux4321** [comment] 2019-11-15 10:05
> Good day!
> 
> In your scenario it's important, that you know when the DOM receives all the loaded data and when the DOM updates. Its possible that you're first trying to scroll but the DOM receives the data afterwards and therefore no scroll operation is happening. Please double check on that.
> 
> Otherwise please try to create a small example on [JsFiddle](https://jsfiddle.net/), this would make it easier to fix the issue for me!

Well, I'm adding the ajax content and setting it to visible inside the success function and then initializing scrollbars and attempting to scroll in the complete function

**Comment by KingSora** [comment] 2019-11-15 10:53
@pollux4321 The problem is, that DOM updates are async. Please try to wrap the scroll call into a `setTimeout` or `requestAnimationFrame` function. This may could also solve the issue.

**Comment by pollux4321** [comment] 2019-11-15 12:06
> @pollux4321 The problem is, that DOM updates are async. Please try to wrap the scroll call into a `setTimeout` or `requestAnimationFrame` function. This may could also solve the issue.

Ok last question, when would I do that? I run an ajax function to get the content and I initialize in the complete function which works great. When do I run a setTimeout? Trying to access the my instance in another function returns not defined. Could you show me how to do that?

**Comment by KingSora** [comment] 2019-11-15 12:12
No problem:
```js
//os init
var osInstance= $(.messages).overlayScrollbars({
  paddingAbsolute : true,
  overflowBehavior : {
    x : 'visible-hidden',
    y : 'scroll'
  },
  scrollbars : {
    autoHide : 'leave',
    autoHideDelay : 100,
  }
}).overlayScrollbars();
//ajax stuff
Ajax.call(function() { 
  //update DOM here...
  //...
  //...

  //scroll stuff
  setTimeout(function() {
    osInstance.scroll({ y : "100%"}) ;
  }, 50);
});
```

**Comment by KingSora** [comment] 2019-11-15 12:25
One more question, to which element are you adding your DOM?

**Comment by pollux4321** [comment] 2019-11-15 13:51
> One more question, to which element are you adding your DOM?

".messages" is being added for the first time to the DOM so I'm getting an error that osInstance is undefined because I'm calling it on something that doesn't exist yet.

**Comment by KingSora** [comment] 2019-11-15 14:10
Well, I dont exactly know how your app works, but I'm certain there is somewhere a small mistake on your side. I've created a small example for you [here](https://jsfiddle.net/wr2v1u4t/1/) maybe this will help you.

**Comment by pollux4321** [comment] 2019-11-15 15:02
> Well, I dont exactly know how your app works, but I'm certain there is somewhere a small mistake on your side. I've created a small example for you [here](https://jsfiddle.net/rdm21xf7/) maybe this will help you.

That works because you already have ".messages" in the DOM. I'm adding ".messages" dynamically with it's content inside and then initializing scrollbars on it. And then also needing to apply the scroll after adding it. You see?

**Comment by KingSora** [comment] 2019-11-15 15:27
@pollux4321 yeah, but that don't really matter... Even if I switch up things to match your scenario it still works: https://jsfiddle.net/93m7e4ch/

Maybe you can create a example where it breaks like in your case, or you can even show me a demo of your app?

**Comment by KingSora** [comment] 2020-01-22 16:09
@pollux4321 Any update on this?

**Comment by KingSora** [comment] 2020-02-05 10:08
@pollux4321 I'll close this issue for now. In case you have any updates on this, please don't hesitate to reopen the issue.

**Closed by KingSora** 2020-02-05 10:08 UTC
