### ISSUE TITLE
Angular initialize plugin to element with max-height

### ISSUE THREAD

**Issue by Harry0411** [KingSora/OverlayScrollbars#107] opened 2019-04-23 09:49 UTC
my code looks like this
  .minview {
	  > .section > .panel-body /deep/ {
	    .table{
        max-height: 21.7vh;
        overflow: auto;
}
}

and I called the selector as
$(".minview").overlayScrollbars({   });

or

$(".minview > .section > .panel-body .table").overlayScrollbars({   });

Both not working

**Comment by KingSora** [comment] 2019-04-23 09:56
Good day!

Please create a small example on [jsfiddle](jsfiddle.net) so I can better identify the issue there.

**Comment by Harry0411** [comment] 2019-04-23 10:11
Hi,
Below is the fiddle for the structure, my project is in angular. So different component loads inside the document.

https://jsfiddle.net/harryharshan/8pygw9ja/1/

Cheers,
Harry

**Comment by KingSora** [comment] 2019-04-23 10:25
Ah alright! The issue is happening because you're using Angular, because if I apply the the plugin to your DOM structure everything is working without problems: https://jsfiddle.net/d79s68cv/

Currently I'm working on a official Angular component, but until then you can create your own.
Just create a new CustomComponent and initialize the plugin in the `ngAfterViewInit` method. To destroy the the plugin, call the destroy method in the `ngOnDestroy` method.

```typescript
import OverlayScrollbars from "overlayscrollbars";

//..........

ngAfterViewInit() {
  this.osInstance = OverlayScrollbars(this.nativeElement, {});
}

ngOnDestroy() {
  if (this.osInstance && this.osInstance.destroy)
    this.osInstance.destroy();
}
```

**Comment by Harry0411** [comment] 2019-04-25 09:04
When will be your Angular scroll will be released. Please let me know.

Cheers,
Harry

**Comment by Harry0411** [comment] 2019-05-03 05:39
is there any update for angular.

**Comment by KingSora** [comment] 2019-05-03 09:04
I'm sorry, I thought I already responded to you last question.
There's currently no update for angluar and no estimated release, because I'll be busy until july with private stuff. But why aren't you building your own angular component with the guidance from me above? Or did I something miss out whats important?

**Comment by KingSora** [comment] 2019-05-15 19:47
@Harry0411 to be more specific, you can paste this code in your project to create a custom angular component, please keep in mind this is just a temporary solution until I've published the official component:

```typescript
import { Component, ElementRef, Input, OnDestroy, AfterViewInit } from "@angular/core";
import OverlayScrollbars from "overlayscrollbars";

@Component({
  selector: "overlay-scrollbars",
  template: "<ng-content></ng-content>",
  styles: [":host { display: block; }"]
})
export class OverlayScrollbarsNgx implements OnDestroy, AfterViewInit {
  @Input() private osOptions: OverlayScrollbars.Options;
  private osTarget: ElementRef;
  osInstance!: OverlayScrollbars;

  constructor(private ref: ElementRef) {
    this.osTarget = ref;
  }

  ngAfterViewInit() {
    this.osInstance = OverlayScrollbars(
      this.osTarget.nativeElement,
      this.osOptions || {}
    );
  }

  ngOnDestroy() {
    if (this.osInstance && this.osInstance.destroy)
      this.osInstance.destroy();
  }
}

```

I'll close this issue in favor of #54 since I'll track there the progress of the framework wrappers.

**Closed by KingSora** 2019-05-15 19:47 UTC
Labels: angular

**Comment by KingSora** [comment] 2019-07-30 22:44
@Harry0411 I've pushed the `angular` component to the repo. Please read my post [here](https://github.com/KingSora/OverlayScrollbars/issues/54#issuecomment-516618253) for further info.
