### ISSUE TITLE
ERROR Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Alessandroinfo** [KingSora/OverlayScrollbars#190] opened 2020-02-21 09:49 UTC
Hi.
I retrieve this error: **ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined** when i  add the module _OverlayscrollbarsModule_.
I use it on _Angular 9_.

**Comment by KingSora** [comment] 2020-02-24 10:47
Good day!

Are you sure this is comming from the library itself? Can you give me the filename and number of the line in which this error is occurring?

**Comment by KingSora** [comment] 2020-02-29 22:09
@Alessandroinfo anything new here?

**Comment by FSDRE** [comment] 2020-03-05 10:33
@KingSora I can confirm the issue:

* Create new NG project with 9.0.5 CLI
* Add overlayscrollbars, overlayscrollbars-ngx and @types/overlayscrollbars
* Add CSS to styles.scss
* Add OverlayscrollbarsModule to imports
* Throw overlay-scrollbars somewhere into the app.component.html
* npm run start

You'll get:

```
core.js:35930 Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (core.js:35930)
    at core.js:35948
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:35944)
    at new NgModuleFactory$1 (core.js:36106)
    at compileNgModuleFactory__POST_R3__ (core.js:41880)
    at PlatformRef.bootstrapModule (core.js:42245)
    at Module../src/main.ts (main.ts:11)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)
```

**Comment by KingSora** [comment] 2020-03-05 11:58
@FSDRE Thank you, I'll try to reproduce it as soon as I have time.

**Comment by FSDRE** [comment] 2020-03-05 12:24
@KingSora Just tried it with the latest NG 8.3.25 and it works. We also have a full blown NG 8.2.14 project running with OS perfectly. So I think we have a 9.x incompatibility issue. Saw a couple libraries fail the last couple of days because NG 9 does so many things differently but most of the issues were not of a very complicated nature. I hope this right here is also an easy one 😄

**Comment by KingSora** [comment] 2020-03-05 16:20
@FSDRE Alright... I'll look into this! :)

**Comment by KingSora** [comment] 2020-03-13 19:26
@Alessandroinfo @FSDRE could you try running the command `npx ngcc`? This should solve the issue.

**Comment by FSDRE** [comment] 2020-03-13 22:37
@KingSora Interesting... I'll try that on monday. But is that a one time compile after installing the npm package or do I have to run it on every `ng serve`?

It really hurts that IE11 is still a thing for certain projects. Could just get rid of the browser property and smile 😄

**Comment by FSDRE** [comment] 2020-03-16 14:05
@KingSora I can confirm that `npx ngcc` works

**Comment by laino** [comment] 2020-03-18 15:23
I removed the ``"browser": ...`` property from ``overlayscrollbars-ngx``'s ``package.json``, ran a clean webpack build, and voila it works.

**Comment by FSDRE** [comment] 2020-03-18 15:26
@laino But the browser property was the fix for #166 so you cannot just remove it again.

**Comment by laino** [comment] 2020-03-18 15:30
I run my entire build through babel anyways, it shouldn't be an issue.

**Comment by FSDRE** [comment] 2020-03-18 15:33
@laino Sure you can help yourself with that but @KingSora needs a general fix for his library to make it run for everybody again.

**Comment by laino** [comment] 2020-03-18 15:35
Yeah I'm not saying you should just remove it in your project. I just left that comment there as input and for the next person stumbling upon on this via google.

**Comment by KingSora** [comment] 2020-03-19 13:34
@laino @FSDRE the fix will probably look like this. The PR for #166 will be reverted in the future. ( see this comment: https://github.com/angular/angular/issues/36062#issuecomment-599055541 )

**Comment by TomTomB** [comment] 2020-04-05 16:05
The issue is probably due to how the library is compiled. Switching to ng-packagr should fix it.  
Until then, there are 2 workarounds:

- Disable Angular Ivy inside the `tsconfig.json` file
```
{
  "compilerOptions": {
    [...]
  },
  "angularCompilerOptions": {
     "enableIvy": false
  }
}
```
- OR: Copy the [overlayscrollbars.component.ts](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-ngx/src/overlayscrollbars.component.ts)  from this library into your own project and use it like a regular component. Don´t forget to remove the `OverlayscrollbarsModule` import from your modules.

**Comment by KingSora** [comment] 2020-04-05 16:41
@TomTomB @FSDRE @laino @Alessandroinfo please try the new `overlayscrollbars-ngx` version `v0.2.2` where this bug should be fixed!

**Comment by KatzeKahn** [comment] 2020-04-06 08:26
@KingSora Your package still requires Angular 7 as dev dependency.

**Comment by KingSora** [comment] 2020-04-06 08:48
@KatzeKahn The package requires Angular 7 as a peerDependency, but its also perfectly useable with higher Angular versions. I need to change that in the next release, youre right...

The Example app is written with Angular 7 but since this is just a example it wasn't a hight priority of mine to update it to v9.. But I'll also change that in the future. Thanks!

**Closed by KingSora** 2020-04-06 08:48 UTC
Labels: :apple: bug, angular

**Comment by FSDRE** [comment] 2020-04-08 09:12
@KingSora I can confirm that it works in NG9 now. There are 2 warnings:

```
Warning: Unable to fully load C:/FS/Visual Studio Code/over/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.component.js for source-map flattening: ENOENT: no such file or directory, lstat 'C:/FS/Visual Studio Code/over/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.component.js.map'

Warning: Unable to fully load C:/FS/Visual Studio Code/over/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.module.js for source-map flattening: ENOENT: no such file or directory, lstat 'C:/FS/Visual Studio Code/over/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.module.js.map'
```

It tries to pull the sourcemaps from `src` instead of `dist`

**Comment by KingSora** [comment] 2020-04-08 10:05
@FSDRE Thanks! Please open a separate issue for this, I'll take a look when I have time.

**Comment by laino** [comment] 2020-04-09 12:44
Working like a charm on our end now.

Thanks!

**Comment by vgreddyrontala** [comment] 2020-10-21 12:30
I got the same issue 

![image](https://user-images.githubusercontent.com/5131391/96719450-06e4a700-13c7-11eb-8bf1-4e7436b5b7b5.png)

the issue because of duplicate module reloading

**Comment by faheemfactor** [comment] 2020-12-16 23:37
Remove NgModule imported in any submodule of the application.

I believe the Ionic Team needs to give more readable messages and tracing the source map better.

**Comment by yasserhennawi** [comment] 2021-01-15 01:39
> @KingSora I can confirm that `npx ngcc` works

You are the hero that we need, thanks you!

**Comment by bennyAngu** [comment] 2021-03-31 05:04
can't resolve still . help to find , thanks in advance[](url)

**Comment by rushifeishi** [comment] 2021-04-20 08:00
I get the same errors.

error detail:
![image](https://user-images.githubusercontent.com/5295278/115358572-6265e500-a1f0-11eb-9cd2-42df18f42e56.png)
error postiion:
![image](https://user-images.githubusercontent.com/5295278/115358720-875a5800-a1f0-11eb-9a2e-4daf59ad9335.png)

So I checked my NgModule imports:
![image](https://user-images.githubusercontent.com/5295278/115358077-e075bc00-a1ef-11eb-8472-48ce4604de67.png)

and, change to :
![image](https://user-images.githubusercontent.com/5295278/115358928-bf619b00-a1f0-11eb-9228-8470a96f9e44.png)
It solved my issue.

**Comment by StevRoger** [comment] 2021-05-17 02:56
I didn't use the scrollbar, but I got the same issue. 
![image](https://user-images.githubusercontent.com/55537405/118426781-14aca180-b6f6-11eb-8599-15b63821ecc7.png)

**Comment by jhuseinovic** [comment] 2021-05-17 17:02
same, and my angular is 8.2.14
![image](https://user-images.githubusercontent.com/8493886/118528182-f2d50e00-b739-11eb-9f54-82a0dca6a68f.png)

**Comment by Ahmed-Hafez** [comment] 2021-07-04 17:25
I have the same issue and it happens when serving the initial project files. No new modules was added, No packages was installed. I did not know the source of the issue.

**Comment by FuadEsgerov** [comment] 2021-07-13 16:49
@Ahmed-Hafez can you find any solution?

**Comment by Ahmed-Hafez** [comment] 2021-07-13 20:26
@FuadEsgerov Unfortunately no, but a temporary solution can be made by uninstalling node modules and reinstalling them. If not solved, replacing the project files into another folder which might solve the issue temporarily. But as I told this is temporary solution and the issue almost will raise again after some time.

**Comment by johnjackson** [comment] 2021-07-16 09:53
rm -rf node_modules
npm install

**Comment by sri5099** [comment] 2021-08-20 17:46
> Good day!
> 
> Are you sure this is comming from the library itself? Can you give me the filename and number of the line in which this error is occurring?

its from lib.es5.d.ts  line number 1340
