### ISSUE TITLE
Scrollbar dragging on mouse hover

### ISSUE THREAD

**Issue by kutaxoff** [KingSora/OverlayScrollbars#512] opened 2023-03-24 11:12 UTC
**Describe the bug**
Often after dragging the scroll with a cursor the scroll will keep reacting on mouse hovering it, which can be stopped by clicking the scroll again.

**To Reproduce**
Steps to reproduce the behaviour:

1.  Create a container with visible scroll
2. Drag the scrollbar up and down with the cursor for a short period of time
3. Release the cursor
4. Move the cursor over the scrollbar without clicking

**Expected behaviour**
The scrollbar should not move on mouse hover.

**Examples**
Example in CodeSandbox - https://codesandbox.io/s/solitary-currying-3ni12n

**Environment**

- Used Operating System(s): macOS Ventura 13.2.1
- Used Browser(s) (with version): Brave 1.49.120 Chromium: 111.0.5563.64 

**Additional context**
Bug was detected in Angular 14 and 15 with overlayscrollbars-ngx 0.4.0

Video example - https://user-images.githubusercontent.com/23554696/227504261-73d0038d-5135-4c90-aae6-5807bd07deda.mov

**Comment by kutaxoff** [comment] 2023-03-24 11:14
https://user-images.githubusercontent.com/23554696/227506717-113d1dae-b6c4-4523-ba23-9bf02f7e8c7f.mov

**Comment by KingSora** [comment] 2023-03-27 15:56
Good day @kutaxoff 

Thats an interesting bug.. I'm not able to reproduce it yet, but I'll try to implement a fix for it.

**Comment by KingSora** [comment] 2023-03-27 17:32
I've released [`v2.1.1`](https://www.npmjs.com/package/overlayscrollbars/v/2.1.1) which hopefully fixes your issue :)

Please try it out and give feedback whether the issue still persists.

**Comment by KingSora** [comment] 2023-04-20 05:13
@kutaxoff I'll close the issue now. In case the fix didn't work please feel free to reopen the issue.

**Closed by KingSora** 2023-04-20 05:13 UTC
Labels: :apple: bug
