### ISSUE TITLE
The content is not being scrolled when the mouse is over the scrollbar

### ISSUE THREAD

**Issue by SourceCipher** [KingSora/OverlayScrollbars#322] opened 2021-04-05 09:15 UTC
**Describe the bug**
When you hover over the scrollbar or its area, using mouse scroll wheel, the content is not scrolled as it should be 

**To Reproduce**
Any demos from https://kingsora.github.io/OverlayScrollbars/#!demos

**Expected behavior**
It should not matter if you hover over the scrollbar, it should always scroll, same as the default scrollbars do or at least have an option to support this

**Comment by KingSora** [comment] 2021-04-05 09:53
Good day @SourceCipher 

I believe this is a duplicate of #128. I'm not sure whether I can do something about it, but I'll try figuring something out.

**Comment by SourceCipher** [comment] 2021-04-05 10:05
Sorry for the duplicate. 

Can you share the solution which can fix this issue even if its only for the webkit? Our project is considering only webkit anyway so that would be a workaround as it seems like this is a big issue as it doesnt work as a native scrollbars and it would be a shame to throw this library away as it the best one which actually works for us from the other many we tried.

Great library, keep it up!

**Comment by KingSora** [comment] 2021-04-05 20:13
The solution I was trying out was to listen to the `wheel` event and as soon as it fired I set the `pointer-events` of `.os-scrollbar` elements to `none`. After a certain time of the `wheel` event not firing the `pointer-events` were set to `auto` again. 

That was like the first idea I got, maybe there is a better approach which also works for Firefox etc.

**Comment by KingSora** [comment] 2021-04-05 20:30
@SourceCipher I've created a small POC for you: https://jsfiddle.net/mjxokuyv/

Its funny, somehow it now also works in Firefox.. does it also work for you?

**Comment by SourceCipher** [comment] 2021-04-08 08:05
@KingSora Its working great on my Opera. I tested even on the MS Edge and it works. I think thats a good workaround

**Comment by KingSora** [comment] 2021-04-08 08:23
@SourceCipher Alright, thanks for your feedback! I'll try to implement it in the next release and in `v2`.

**Comment by KingSora** [comment] 2022-11-12 12:03
This should be fixed in `v2` which released today :)

**Closed by KingSora** 2022-11-12 12:03 UTC
Labels: :pear: enhancement, :honey_pot: workaround
