### ISSUE TITLE
iOS-Safari - flickering, black squares when scrolling on body element

### ISSUE THREAD

**Issue by Acccent** [KingSora/OverlayScrollbars#61] opened 2018-09-23 20:59 UTC
Hi,

First of all I wanna thank you because I think this is the best scrollbar plugin there is, which is no small feat.

I have an issue where my website flickers or shows black areas when scrolling on iOS (it works perfectly on Windows, haven't tested on Android and Mac). For instance when scrolling down, the bottom of the screen that comes into view can be black for half a sec before rendering.

Attached are some pictures that show the problem. The ones where there is a black area is when I instantiate OS on the body element, the ones where the background image is still visible but the content is clipped are when OS is instantiated on the div right below the body.
(The blur/smudge is just for NDA reasons, the text and content renders fine once it does render.)

I tried removing all position:fixed elements as I thought this might cause the problem, but no dice.
Any ideas?

<img width="188" src="https://user-images.githubusercontent.com/7839128/45932900-c0a38c00-bf51-11e8-9958-700872f08059.png"> <img width="188" src="https://user-images.githubusercontent.com/7839128/45932901-c0a38c00-bf51-11e8-8eef-89443e87a1ff.PNG"> <img width="188" src="https://user-images.githubusercontent.com/7839128/45932902-c0a38c00-bf51-11e8-9f7c-e02c9bcdc2aa.PNG"> <img width="188" src="https://user-images.githubusercontent.com/7839128/45932903-c0a38c00-bf51-11e8-9bfe-16bd25dd39da.PNG"> <img width="188" src="https://user-images.githubusercontent.com/7839128/45932904-c0a38c00-bf51-11e8-98f5-58dec7bc45b7.PNG">

**Comment by Acccent** [comment] 2018-09-24 06:05
Hi, so!

Disabling the plugin does make the issue disappear.
Changing the -webkit-overflow-scrolling CSS rule also fixes it, but then the scrolling is very "sticky", as you probably know, so it's not a good solution...

When experimenting, I found that `nativeScrollbarsOverlaid: { showNativeScrollbars: true }` also did fix the issue. Now the scrolling is smooth and there is no flickering. However the address bar never collapses, as it does normally when you scroll down. It's a minor issue but still strange and not ideal.

When opening the documentation pages, everything works beautifully, scrolling is smooth with no flickering and the address bar collapses as expected.

**Comment by KingSora** [comment] 2018-09-24 07:52
Alright!

I've searched this up on google, and many other people have the same issue. It seems to be a annoying bug which is appearing in iOS-Safari. According to some people, the following CSS rules could solve the problem:
```css
.os-viewport {
    -webkit-backface-visibility: hidden;
    -webkit-transform: translate3d(0,0,0);
}
```
Please try this out, but I don't think this will change much.

Since `nativeScrollbarsOverlaid: { showNativeScrollbars: true }` fixed the problem, please try to remove the scrollbar theme with `className : null` or by deleting all [styles below line 272.](https://github.com/KingSora/OverlayScrollbars/blob/master/css/OverlayScrollbars.css#L272). Maybe this will help.

Now a small explanation to why the adress bar never collapses with the `nativeScrollbarsOverlaid: { showNativeScrollbars: true }` option. The `body` element is special. It has native event-bindings to the browser. For example in chrome you have the `pull to refresh` gesture, which refreshes the website if you keep pulling the website. This and propably many other features are bound to the scroll-event on the body element itself. And here comes the problem, if you initialize the plugin to the body element, the `overflow` style of it is set to `hidden` and the body element becomes a wrapper element for the plugin elements. So the actual body element will never fire a scroll event and the browser will never dispatch features which are bound to that.

Thats why I highly recommend you to use the option I described in my first answer. Mobile browsers simply have a better user experience with this option. I'm working on a solution for this though, so that the plugin somehow forwards scroll-events somehow to the body element.

**Comment by Acccent** [comment] 2018-09-24 17:48
Hey again,

thanks for the very quick responses :) I appreciate it.

I'll go ahead and just disable the instantiation for mobile, like you suggest. I was already using a custom theme, so I'm not too keen on messing with the CSS more.

Looking forward to seeing a solution that takes care of this! I'm subscribed to this issue, so while I don't have time to do more testing now, I can help in the future to see if later versions still have the same problem :)

**Comment by KingSora** [comment] 2018-09-25 18:37
Well, since this is more of a browser problem than a problem of the plugin, I can't do much against it. Nevertheless I'll try my best to fix this issue! :)

**Comment by MarcosRakesh** [comment] 2018-10-10 08:02
> I'm working on a solution for this though, so that the plugin somehow forwards scroll-events somehow to the body element.

Any progress? With `nicescroll` you can use scroll-events to the body element.

**Comment by KingSora** [comment] 2018-10-10 18:03
@MarcosRakesh I'm not sure whether you fully understood the problem were have discussed here, beause I've tested the latest `nicescroll` version and the problem isn't fixed.

Just for clarification, you can use `OverlayScrollbars` on the body element and you can also catch any `scroll` events which are made. They just won't fire directly on the body element (but on a wrapper element) thats why the browser can't dispatch any native implemented logic which is depending on this `scroll` event which is supposed to fire on the body element.

**Comment by KingSora** [comment] 2019-08-09 07:18
@Acccent Good news, I've found [this](https://www.chromestatus.com/feature/4533350404456448) new feature in chrome which will make it possible to enable `pull to refresh` and `url-bar hiding` with the plugin, because I'll be able to specify the element which the browser is treating as root-scroller element.

**Comment by KingSora** [comment] 2022-11-12 12:10
This should be (hopefully) fixed in `v2` which released today :)

**Closed by KingSora** 2022-11-12 12:10 UTC
Labels: :pear: enhancement, :honey_pot: workaround

**Comment by bpetrov98** [comment] 2024-04-22 13:15
@KingSora the backface-visibility and transform property fixed the issue for me. Thanks @KingSora :)
