### ISSUE TITLE
Question: getting "import/no-unresolved" with eslint in TypeScript project

### ISSUE THREAD

**Issue by maurocolella** [KingSora/OverlayScrollbars#570] opened 2023-10-12 01:32 UTC
Hi,

I am struggling to get TypeScript to resolve this export/module, and I wasn't sure how to ask for help.

**Comment by benz2012** [comment] 2023-10-16 03:54
Me too, and originally I thought it was an real import error however I see the CSS resolving in my build output. I don't believe TypeScript is relevant to the issue.

For me the steps to reproduce were
1. spin up a project with create-react-app
2. `npm install overlayscrollbars`
3.  Within any source js/jsx file in the tree: `import 'overlayscrollbars/overlayscrollbars.css'`

Which gives
> Unable to resolve path to module 'overlayscrollbars/overlayscrollbars.css'  import/no-unresolved

Given that this seems to be a newer NodeJS import feature due to the note in the README about using a different import for older Node version, it makes me think that this might be an issue with ESLint itself 🤷

**Comment by KingSora** [comment] 2023-10-16 15:19
Good day @maurocolella 

Do you have any example code for me? What packages did you install and which node version are you using?

**Comment by benz2012** [comment] 2023-10-16 16:24
Upgrading to Latest Node Stable of `v18.18.2` resolves the issue in my run/build. Although still seeing the error in VSCode but that's not an issue for your library

**Comment by benz2012** [comment] 2023-10-16 17:12
I've even tried ejecting the CRA and then manually upgrading eslint and eslint-webpack-plugin, but that didn't resolve the issue. Basically, I'm curious if CRA is core to the issue here, and was hoping to _not_ have to spin up a React project from scratch to test that assumption, lol

**Comment by KingSora** [comment] 2023-10-16 17:29
@maurocolella @benz2012 I believe you two have the same issue here. Turns out this is a known issue for eslint and CRA:
- https://github.com/facebook/create-react-app/issues/10892
- https://github.com/import-js/eslint-plugin-import/issues/1810

As long as your build works you could just do something like:
```js
// eslint-disable-next-line import/no-unresolved
import 'overlayscrollbars/overlayscrollbars.css';
```

But since this is a little bit unsatisfactory I've made some compatibility changes in the newest version `v2.4.1` where you can now always use the path `import 'overlayscrollbars/styles/overlayscrollbars.css';` regardless of your environment.

So going forward `'overlayscrollbars/styles/overlayscrollbars.css'` will always work, while `'overlayscrollbars/overlayscrollbars.css'` only works if the bundler and your linter know how to handle the `exports` field in the `package.json`.

**Comment by benz2012** [comment] 2023-10-16 17:50
Awesome! Confirming it works for me in `v2.4.1`. Thank you

**Comment by KingSora** [comment] 2023-10-19 07:50
@maurocolella I'll close this issue for now.. In case your problem is not solved please don't hesitate to give feedback here or to open a new issue.

**Closed by KingSora** 2023-10-19 07:50 UTC

**Comment by maurocolella** [comment] 2023-10-21 01:42
Appreciate it, thanks. Just wanted to note that I am not using `create-react-app`, but if this resolves typings for other users, then fantastic! I am thankful.
