### ISSUE TITLE
Unable to scroll if container isn't scrollable on mount

### ISSUE THREAD

**Issue by hlynurstef** [KingSora/OverlayScrollbars#578] opened 2023-10-19 15:41 UTC
**Describe the bug**
The content is sometimes not scrollable depending on the container height on mount or if the container height changes through resizing the browser window

**To Reproduce**
Reproduction demo:

https://codesandbox.io/p/sandbox/overlayscrollbars-react-example-forked-skjq7t?file=%2Fsrc%2FApp.tsx%3A10%2C39
https://skjq7t-5173.csb.app/

https://github.com/KingSora/OverlayScrollbars/assets/15615089/f94eb75c-82c8-4d01-afbb-a44517eebbfd

1. Open the reproduction demo
2. Resize the window smaller so that it overflows the container
3. Reload the page
4. See that it can be scrolled
5. Resize your window so that the red box stops overflowing
6. Resize the window back so that the red box overflows
7. Notice the scroll doesn't work anymore
8. See attached video for demonstration

Also try:
1. Resizing the window so that the red box doesn't overflow
2. Reload the page
3. No scroll (expected)
4. Resize the window so that the red box overflows
5. No scroll (not expected)

**Expected behavior**
The scroll should appear if the window is resized causing overflow

**Environment**

- Used Operating System(s): macOs 14.0
- Used Browser(s) (with version): Chrome Version 118.0.5993.70 (Official Build) (arm64)

**Comment by KingSora** [comment] 2023-10-19 16:02
@hlynurstef Thanks for the report! Thats a regression since `v2.4.0`.. I'll release a fix as quick as possible

**Comment by KingSora** [comment] 2023-10-20 07:51
@hlynurstef This should be fixed in the newest version [`v2.4.3`](https://www.npmjs.com/package/overlayscrollbars/v/2.4.3).

**Closed** 2023-10-20 07:54 UTC
Labels: :apple: bug

**Comment by hlynurstef** [comment] 2023-10-20 09:02
@KingSora thanks for the quick fix!

**Comment by KingSora** [comment] 2023-10-20 09:53
@hlynurstef you're welcome! :)
