### ISSUE TITLE
The scroller breaks if you drag'n'drop it outside the scroll area

### ISSUE THREAD

**Issue by IgorLesnevskiy** [KingSora/OverlayScrollbars#18] opened 2018-03-20 12:01 UTC
Hello!
I found this bug on all my projects. You can see it on your demo page too - http://take.ms/WhYhS
00:00 - 00:05   everything is fine
00:05 - 00:09   I've dragged the scrollbar outside the box
00:10 - 00:26   the scrollbar has become crazy

**Comment by KingSora** [comment] 2018-03-20 13:16
Good day!

That seems really weird. I need a bit more info because I can't reproduce this behavior.
- Which Browser are you using? (Browser and version please)
- Does this happen on other browsers too?
- Which Operating System are you using?
- Did you press any buttons during this drag&drop? Can you write any buttonpresses you've done?
- Is there any error in the console?
- If you trigger this behavior and press the left mouse button on the handle, does this behavior still remain?
- Did you find any way to fix this if this bug occured (any button presses and so on)?

Once I know all these, I can investigate in this... it seems really weird though.

**Comment by IgorLesnevskiy** [comment] 2018-03-20 13:35
Well, I solved the problem. The problem was related to Tampermonkey extension for Google Chrome. It sounds strange, but after I turned off the extension - the problem is disappeared.
Sorry that I wasted your time.

**Comment by IgorLesnevskiy** [comment] 2018-03-20 13:45
Well, the only custom script I have is the SaveFrom.net Helper - http://take.ms/kVY4k. And when I turned it off - everything is became back to normal. ¯\_(ツ)_/¯

**Comment by KingSora** [comment] 2018-03-20 14:15
Glad to hear that!

I'll install this plugins too and will try to reproduce it and to fix it. Even if this bug is only present if you have this specific setup I'll try to fix it, because I wanna offer a plugin which is able to work in every enviroment.

If you want to help me, please tell me which buttons you've pressed to abort the drag&drop process, because on the video it seems like you've aborted it with some kind of keypress.

Thank you! :)

**Comment by IgorLesnevskiy** [comment] 2018-03-20 16:07
Glad to see your enthusiasm)
I make it in three simple steps:
1. press the Left Mouse Button over the scrollbar
2. move the cursor outside the box area
3. unpress the Left Mouse Button

**Comment by KingSora** [comment] 2018-03-20 19:22
Alright, after a very long investigation I think I've found the issue. It has to do with passive events and how I was removing them. I don't know exactly why it happened with this script but I've fixed it for sure.

This fix will be implemented in `version 1.4.1`. Thank you very much! :)
If you have other issues, please don't hesitate to report them.

**Comment by KingSora** [comment] 2018-03-20 20:13
I've uploaded a demo of the fix to my documentation page: https://kingsora.github.io/OverlayScrollbars/#!demos/basic
Please try to trigger this bug again, and confirm if the big is fixed or not.

Thank you!

**Comment by IgorLesnevskiy** [comment] 2018-03-20 20:20
I'm very grateful to you for so quick bug fix! 
Thank you, I'll check it tomorrow and let you know the results.

**Comment by IgorLesnevskiy** [comment] 2018-03-21 09:25
Good day!
Well, as I can see, the problem was resolved :-)

**Comment by KingSora** [comment] 2018-03-21 09:38
Perfect! :)

I'll close the issue after `version 1.4.1` was released, because technically the fix isn't out yet.

**Comment by KingSora** [comment] 2018-03-22 21:31
The release is here: https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.4.1

Once again, thank you! :)

**Closed by KingSora** 2018-03-22 21:31 UTC
Labels: :apple: bug
